### PR TITLE
feat: support symbolicating windows crashes

### PR DESCRIPTION
**Pull request by indutny**
This is a long shot, but since this script already has all necessary tools to symbolicate text versions and the patch is very minimal, I thought we could add support for Windows crashes as well.

We have been using this patched version of symbolicate-mac internally for awhile, and our tooling can format Windows crashes in the way that is compatible with it. Perhaps, it'll be useful for others too!

### CODE REVIEW

**Review by MarshallOfSound — COMMENTED** [review]
This module does have uh, awkward naming to add this as a feature 😆 But the code is so small we could land it 🙃

**Comment by indutny** [comment]
That was my thought process as well 😅 I feel like renaming or forking the module for the sake of one line change is too much

**Comment by indutny-signal** [comment]
Sorry for a delay!

Our pipeline is:

1. Use minidump crate to parse local dump
2. Remove everything except stack trace and thread information from the dump
3. Output it to debug log in json

Then we have a separate script that converts that json to the format that is compatible with symbolicate-mac. So... is it standard? Yeah, sort of! Do we make it happen so - for sure :)

We currently float a patch-package patch to add this one-line change, so I'd love to get us to a place where it isn't necessary. Thanks!

**Review by nornagon — APPROVED** [review]
this seems pretty niche but the change is small and it comes with tests so why not i suppose :)

**Comment by indutny-signal** [comment]
Aw, you are the best! Thank you!

**Pull request merged**
